---
title: "Tutorial on BLISS Downstream Analysis"
author: Federico Agostini
output:
    github_document:
        fig_width: 12
        fig_height: 5
        pandoc_args: [
            "--output=README.md"
        ] 
---

```{r setupEnv, include=FALSE}
working.folder = "./"

knitr::opts_knit$set(root.dir = working.folder)
knitr::opts_chunk$set(echo = FALSE)

if( interactive() )
    setwd(working.folder)

species = "Homo sapiens"
genome = "hg19"
annotation = "90"
```

```{r loadPackages, message=FALSE, results="hide"}
require("AnnotationHub")
require("biomaRt")
require("GenomicFeatures")
require("rtracklayer")
require("data.table")
require("knitr")
require("ggplot2")
require("ggpubr")
require("ggsci")
require("scales")
```

```{r customFunction}
countOverlapsWeighted <- function(query, subject){
    overlaps = as.data.table(findOverlaps(query, subject))
    overlaps[, N := .N, by="subjectHits"]
    overlaps = overlaps[N == 1,]
    setkey(overlaps, subjectHits)
    tmp = data.table(as.data.frame(subject), index = seq_along(subject), key="index")
    overlaps[tmp, score := score]
    setkey(overlaps, queryHits)
    overlaps = overlaps[, .(score = sum(score)), by=key(overlaps)]
    tmp = data.table(as.data.frame(subject), index = seq_along(subject), key="index")
    tmp[overlaps, score := score]
    tmp[is.na(score), score := 0]
    return(tmp[, score])
}
```

```{r sampleTable}
sampleTable = data.table(name = c("BB61_DMSO_1", "BB62_DMSO_2", "BB61_ETO_1", "BB62_ETO_2"),
    Experiment = c("BB61", "BB62", "BB61", "BB62"),
    Treatment = c("DMSO", "DMSO", "ETO", "ETO"),
    Replicate = c("1", "2", "1", "2"),
    path=c("./data/BB61_TK6DMSOrep1_CATCACGC_chr-loc-countDifferentUMI.bed.gz",
    "./data/BB62_TK6DMSOrep2_CATCACGC_chr-loc-countDifferentUMI.bed.gz",
    "./data/BB61_TK6ETOrep1_GTCGTCGC_chr-loc-countDifferentUMI.bed.gz",
    "./data/BB62_TK6ETOrep2_GTCGTCGC_chr-loc-countDifferentUMI.bed.gz"))
```

```{r loadData}
data = lapply(with(sampleTable, setNames(path, name)), 
    function(x){
    tmp = fread(cmd=paste("gunzip -c", x),
        col.names=c("seqnames", "start", "end", "score"),
        colClasses=c("character", "numeric", "numeric", "numeric"))
    # tmp[seqnames==20, seqnames := "X"][seqnames==21, seqnames := "Y"][seqnames==22, seqnames := "MT"]
    return(tmp)
})

pl = rbindlist(data, idcol="name")
pl = pl[, lapply(1:10, function(x) .SD[score>=x, .N]), by="name"]
pl = melt.data.table(pl, id.vars="name")
pl[, variable := as.numeric(gsub("V", "", variable))]
pl[, c("Experiment", "Treatment", "Replicate") := tstrsplit(name, "_")]
```

```{r fig1a}
fig1a = ggplot(pl, aes(x=variable, y=value, col=Treatment, shape=Replicate)) +
    ggtitle("TK6 Cells") +
    geom_point(size=3) + geom_line(lwd=0.75) +
    scale_x_continuous("at least # UMIs per location", breaks=1:10) +
    scale_y_log10("DSB locations") +
    scale_colour_npg() +
    theme_bw() + theme(plot.title=element_text(hjust=0.5))
fig1a
```

```{r createGenomicBins}
chrom_sizes = getChromInfoFromBiomart(biomart="ENSEMBL_MART_ENSEMBL",
                             dataset="hsapiens_gene_ensembl",
                             host="http://feb2014.archive.ensembl.org")
chrom_sizes = with(chrom_sizes, Seqinfo(seqnames=as.character(chrom), seqlengths=length, isCircular=NA, genome=genome))
chrom_sizes = keepStandardChromosomes(chrom_sizes)

genomic_tiles = tileGenome(seqlengths(chrom_sizes), tilewidth=2e3, cut.last.tile.in.chrom=TRUE)
genomic_tiles = genomic_tiles[width(genomic_tiles)==2e3]

pl = sapply(data,
    function(x)
    countOverlaps(genomic_tiles,
        with(x, GRanges(seqnames, IRanges(start, width=1), score=score))))

pl = cor(pl[rowSums(pl)>0,])

pl[lower.tri(pl)] = NA

pl = melt.data.table(data.table(pl, keep.rownames = "Row"),
		id.vars = "Row", variable.name = "Col", value.name = "Value")

pl[, Col := factor(Col, levels = sampleTable[, name])]
pl[, Row := factor(Row, levels = sampleTable[, name])]

fig1b = ggplot(pl, aes(x = Col, y = Row)) +
    ggtitle("Breaks (2 kb window size)") +
    geom_tile(data = subset(pl, !is.na(Value)), aes(fill = Value), col="white", lwd=1) +
    geom_tile(data = subset(pl, is.na(Value)), fill = "white") +
    scale_fill_gsea(name="Pearson\nCorrelation", limits=c(0,1)) +
    geom_text(aes(label=round(Value, 3), family="Helvetica", fontface="bold")) +
    theme_pubclean() +
	theme(plot.title=element_text(hjust=0.5), legend.position=c(0.2, 0.8),
	axis.ticks=element_blank(), panel.grid=element_blank(), axis.title=element_blank())
fig1b
```

```{r}

```